name: Automation

on:
  issues:
    types: [opened, reopen]
  pull_request:
    types: [opened]
env:
  MY_GITHUB_TOKEN: ${{ secrets.GHBOT_TOKEN }}

jobs:
  projectassignment:
    runs-on: ubuntu-latest
    name: Add to Terraform project
    steps:
    - name: Project automation
      uses: crayon/composite-projectautomation@v1.0.0-beta1
      with:
        project_number: 7
        id: ${{ github.event.pull_request.node_id || github.event.issue.node_id }}
